version: "3.9"
services:
  postgres:
    image: postgres:16.3
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - postgresN
    volumes:
      - db-data:/etc/data
  backend:
    build:
      context: .
      dockerfile: ./nestjs-database-messages/Dockerfile
    depends_on:
      - postgres
    networks:
      - postgresN
    ports:
      - ${REACT_APP_BACKEND_PORT}:${REACT_APP_BACKEND_PORT}

  client:
    build:
      context: .
      dockerfile: ./react-ts-message/Dockerfile
    depends_on:
      - backend
    ports:
      - ${PORT}:${PORT}
networks:
  postgresN:
volumes:
  db-data:
